_wandb:
    value:
        cli_version: 0.28.0
        e:
            8fhjocvkw6v5jweez99m5jycc5oekysa:
                args:
                    - --policy_learning
                    - RUDDER
                    - --seeds
                    - "0"
                    - "1"
                    - "2"
                    - "3"
                    - "4"
                    - "5"
                    - "6"
                    - "7"
                    - "8"
                    - "9"
                codePath: Code\Rudder\Vcbm\rudder-demonstration-code-master\watch_repair.py
                codePathLocal: watch_repair.py
                email: iprathapselva@gmail.com
                executable: C:\Users\prath\AppData\Local\Python\pythoncore-3.14-64\python.exe
                git:
                    commit: 7765d902385bbe85c2959caf48773b1eb5820c1b
                    remote: https://github.com/prathapselvakumar/Postgraduate-Dissertation.git
                host: DESKTOP-2S12E5B
                os: Windows-11-10.0.26200-SP0
                program: D:\Presentations\Masters Data\Postgraduate-Dissertation\Code\Rudder\Vcbm\rudder-demonstration-code-master\watch_repair.py
                python: CPython 3.14.6
                root: D:\Presentations\Masters Data\Postgraduate-Dissertation\Code\Rudder\Vcbm\rudder-demonstration-code-master
                startedAt: "2026-07-10T14:26:47.738740Z"
                writerId: 8fhjocvkw6v5jweez99m5jycc5oekysa
        m: []
        python_version: 3.14.6
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
            "4": 3.14.6
            "5": 0.28.0
            "8":
                - 3
            "10":
                - 20
            "12": 0.28.0
            "13": windows-amd64
n_seeds:
    value: 10
policy_learning:
    value: RUDDER
